name: saph-convert
packagePath: .
monoRepo: false
commitMessageTemplate: 'chore(release): release {{new-version}}'
tagTemplate: v{{new-version}}
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
githubRepo: fearandesire/saph-convert
